name: flutter_signature_pad
description: Flutter widget to allow users to sign with finger and export the result as image.
version: 3.0.1
homepage: https://github.com/kiwi-bop/flutter_signature_pad.git

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=2.2.2"

